inherit_from:
  - https://raw.githubusercontent.com/houndci/hound/master/.ruby-style.yml

AllCops:
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "Guardfile"
  DisplayCopNames: true
