language: ruby
rvm:
  - 2.4.1
bundler_args: "--without production --deployment --jobs=4"
cache:
  bundler: true
  directories:
    - node_modules
sudo: false
branches:
  only:
    - master
env:
  - DB=mysql
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rake db:drop db:create db:migrate db:seed
  - bundle exec rake spec SPEC_OPTS="--color --format documentation"
notifications:
  email: false
  slack:
    secure: EcFePORCJKIusovo9JYenApcXhdv8TEFaOai7hW1rkn9mPgyx7022+hi2Id6EC7G+9LMbG/VEV50guNkn63t5e9jA74XTM94KOio6a6aLm5U8veuUSqqWynTeJTny6jXWHW4PigDru8jf3Hr4m0xWjokrnP44tHEE16WX14lK9I=
