sudo: false
language: ruby
rvm:
  - 2.4.1
bundler_args: "--without production --deployment --jobs=4"
cache:
  bundler: true
  directories:
    - vendor/bundle
    - node_modules
  yarn: true
branches:
  only:
    - master

before_install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - |
    echo -e "[mysqld]
    character_set_server=utf8mb4
    collation_server=utf8mb4_unicode_ci
    innodb_large_prefix=ON
    innodb_file_format=Barracuda
    innodb_file_format_max=Barracuda" | sudo tee /etc/mysql/conf.d/travis.cnf
  - sudo /etc/init.d/mysql restart
script:
  - bundle exec rake db:drop db:create db:migrate db:seed
  - bundle exec rake spec SPEC_OPTS="--color --format documentation"
notifications:
  email: false
  slack:
    secure: EcFePORCJKIusovo9JYenApcXhdv8TEFaOai7hW1rkn9mPgyx7022+hi2Id6EC7G+9LMbG/VEV50guNkn63t5e9jA74XTM94KOio6a6aLm5U8veuUSqqWynTeJTny6jXWHW4PigDru8jf3Hr4m0xWjokrnP44tHEE16WX14lK9I=
