language: ruby
rvm:
  - 2.2.1
bundler_args: --without development
sudo: false
cache: bundler
env:
  - DB=mysql
script:
  - bundle exec rake db:drop db:create db:migrate db:seed
  - bundle exec rake spec
notifications:
  email: false
