development:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me_development
  username:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me_test
  username:
  host: 127.0.0.1

staging:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me_staging
  username: root
  password:
  host: staging.kurorekishi.me
  reconnect: true
  pool: 1

production:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me
  username: kurorekishi_me
  password: kurorekishi_me
  host: kurorekishi-me.c3worgholwhq.us-east-1.rds.amazonaws.com
  reconnect: true
  pool: 1
