development:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me_development
  username:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me_test
  username:
  host: 127.0.0.1

staging:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me_staging
  username: root
  password:
  reconnect: true
  host: staging.kurorekishi.me
  pool: 1

production:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me
  username: kurorekishi_me
  password: kurorekishi_me
  reconnect: true
  host: clean-them-all.c2rcsjiokdyj.ap-northeast-1.rds.amazonaws.com
  pool: 1
