development:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_development
  username: root
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_test
  username: root
  host: 127.0.0.1

staging:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_staging
  username: root
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8mb4
  database: kurorekishi_me
  username: kurorekishi_me
  password: kurorekishi_me
  host: kurorekishi-me-20171009.c4njtcfohxnr.ap-northeast-1.rds.amazonaws.com
  pool: 16
