development:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_development
  username:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_test
  username:
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all
  username: clean_them_all
  password: clean_them_all
  reconnect: true
  host: clean-them-all.c2rcsjiokdyj.ap-northeast-1.rds.amazonaws.com
  pool: 1
