development:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_development
  username:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_test
  username:
  host: 127.0.0.1

staging:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_staging
  username: root
  password:
  host: 127.0.0.1
  reconnect: true
  pool: 1

production:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all
  username: kurorekishi_me
  password: kurorekishi_me
  host: kurorekishi.c3worgholwhq.us-east-1.rds.amazonaws.com
  reconnect: true
  pool: 1
