development:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_development
  username: root
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_test
  username: root
  host: 127.0.0.1

staging:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all_staging
  username: root
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8mb4
  database: clean_them_all
  username: clean_them_all
  password: clean_them_all
  host: clean-them-all-20170709-cluster.cluster-c3worgholwhq.us-east-1.rds.amazonaws.com:3306
  pool: 16
