start_message:
  - 'ツイ消ししちゃお ꉂꉂƱʊ꒰>ꈊ<ૢ꒱❣❣ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - '｡ஐஃツイ消しནʓネヾ(öᴗ<๑)｡ஐஃ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消し中 (ꈨຶꎁꈨຶ)۶" ꁖʓ╵᷅ժ ̀꒭~ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - '(╭☞•́⍛•̀)╭☞ 今からツイ消ししまーっす | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消しせねばっ =͟͟͞͞(๑•̀ㅁ•́ฅ✧ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消しにきました ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消しします (˚ ˃̣̣̥ω˂̣̣̥ )  | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
finish_message:
  - 'ツイ消ししちゃった ꒰ •ॢ ̫ -ॢ๑꒱✩ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消ししたよ (◍⁃͈ᴗ•͈)४४४♡* | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消し完了 (๑‾᷆д‾᷇๑)৳৸ᵃᵑᵏ Ꮍ৹੫ᵎ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消ししましたが、なにか？ ʕ •́؈•̀ ₎ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消し終わった (๐ ́꒪̐ꈊ͒꒪̐)ꐳ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消し終わりましたー ʕु•̫͡•ʔु ✧ | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
  - 'ツイ消ししましたっ ˚‧º·(˚ ˃̣̣̥⌓˂̣̣̥ )‧º·˚  | 呪われしツイートを一括削除！ 黒歴史クリーナー - http://kurorekishi.me/cleaner #黒歴史クリーナー'
